### ISSUE TITLE
Comp_cui.py

### ISSUE THREAD

**Issue by wpdrx** [RomainFeron/UMLS_Tagging#11]
Incohérence # relevant elements sur jeu de donnée fourni (liste1.txt vs liste2.txt)

=> fonction nb_match_two_dic( bugguée)

**Comment by wpdrx** [comment]
normalement OK
juste vérifier la formule de rappel / précision

**Comment by RomainFeron** [comment]
OK je regarde ça
C'est dommage, hier j'ai pull sur git avant que tu fasses les modifs donc y'a pas les légendes dans les output de cette nuit :(
